### ISSUE TITLE
Avoid saving pickle file

### ISSUE THREAD

**Issue by jonmmease** [jonmmease/hilbert_frame#2]
Would it be possible to move the data stored in the custom pickle file in the hframe directory into custom parquet metadata?  If so, we could get rid of the `something.hframe` directory altogether.  I'm not sure of the status of saving custom metadata to parquet using the fastparquet and pyarrow engines though.

References:
 - https://ndolgov.blogspot.com/2016/10/parquet-file-metadata-standard-and.html
 - https://github.com/dask/fastparquet/issues/343

**Comment by jonmmease** [comment]
I think I've worked out a way to store custom metadata in the parquet file set using fastparquet.  For example:

```python
# Imports
from fastparquet import write, ParquetFile, parquet_thrift
from fastparquet.writer import write_common_metadata

import copy
import os
import json

import pandas as pd
import numpy as np

# Create sample data
N=50
df = pd.DataFrame({
    'a': np.arange(N),
    'b': np.linspace(0, 10, N),
    'c': np.random.rand(N),
})

# Write parquet file with `'hive'` file_schema like dask does
write('outfile_hive.parq', df, row_group_offsets=10, file_scheme='hive')

# Open file
basepath = 'outfile_hive.parq'
pf = ParquetFile(basepath)

# Add a new property to the file metadata
new_fmd = copy.copy(pf.fmd)
new_kv = parquet_thrift.KeyValue()
new_kv.key = 'hello'
new_kv.value = json.dumps({'world': [1, 2], 'country': ['X', 'Y']})
new_fmd.key_value_metadata.append(new_kv)

# Overwrite file metadata
fn = os.path.join(basepath, '_metadata')
fastparquet.writer.write_common_metadata(fn, new_fmd, no_row_groups=False)

fn = os.path.join(basepath, '_common_metadata')
fastparquet.writer.write_common_metadata(fn, new_fmd)

# Reopen file
pf2 = ParquetFile(basepath)
pf2

# Access custom metadata
props = json.loads(pf2.key_value_metadata['hello'])
props
```
```
{'world': [1, 2], 'country': ['X', 'Y']}
```

@jbednar @philippjfr  Is it alright for `HilbertFrame` to require fastparquet and not support pyarrow (at least initially)?

**Comment by jbednar** [comment]
Yes, that's fine.  Can it not simply recreate the necessary data if it's not restored with the file, so that fastparquet makes it faster to get started but gives the same results?  Or will having the data in the file confuse pyarrow?

**Comment by jonmmease** [comment]
Done in dfb02daa6763ce1262cabdb74ee87a543ccbaf97
